spring.application.name=Leson05
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_maganer
    username: root
    password: phuongdong2702
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update